name: calendart
description: High customizable Flutter calendar widgets with popup view and multi-columns/rows of months, multi-scroll directions, multi-selections.
version: 1.0.7
homepage: https://github.com/creomobile/calendart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # combos: ^1.2.0
  combos:
    git:
      url: https://github.com/la-developers/combos

dev_dependencies:
  pedantic: ^1.8.0

flutter:
